# Generated by Django 3.1.2 on 2020-10-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBirth', models.DateField()),
                ('website', models.URLField()),
                ('phone_number', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='Profile/')),
                ('Age', models.IntegerField()),
                ('freelance', models.CharField(choices=[('Avaliable', 'Avaliable'), ('Not Avaliable', 'Not Avaliable')], max_length=20)),
                ('degree', models.CharField(max_length=80)),
                ('about', models.TextField(max_length=2000)),
                ('about_sous', models.TextField(max_length=1000)),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
