# Generated by Django 3.1.2 on 2020-10-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='Description',
        ),
    ]
