# Generated by Django 3.1.2 on 2020-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20201028_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_type', models.CharField(choices=[('fas fa-mobile-alt', 'Mobile App'), ('fas fa-desktop', 'Desktop App'), ('fas fa-globe', 'Web App')], max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
