# Generated by Django 3.1.2 on 2020-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
