# Generated by Django 3.1.2 on 2020-11-05 16:59

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTIMONIALS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('work', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to=Home.models.Image_upload2)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
